name: FCS Image Scanning with Enforcement

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e #v4.3.0

      - name: Build Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a #v7.3.0
        with:
          context: ./image-scan
          file: ./image-scan/Dockerfile
          tags: crwd/ubuntuweb:latest
          push: false
          load: true

      - name: Download and Setup FCS CLI
        id: fcs-setup
        env:
          FCS_CLIENT_ID: ${{ vars.FCS_CLIENT_ID }}
          FCS_CLIENT_SECRET: ${{ secrets.FCS_CLIENT_SECRET }}
          FALCON_REGION: ${{ vars.FALCON_REGION }}
          FCS_BIN_PATH: /home/runner/.local/bin/fcs        
        run: |
          chmod +x ./fcs_download_standalone.sh
          ./fcs_download_standalone.sh

      - name: Run FCS Image Scan
        id: fcs
        run: |
          export FCS_EXIT_CODE=0
          /home/runner/.local/bin/fcs/fcs scan image crwd/ubuntuweb:latest --output ./image-scan-results.sarif --format sarif --upload --client-id "${{ vars.FCS_CLIENT_ID }}" --client-secret "${{ secrets.FCS_CLIENT_SECRET }}" --falcon-region "${{ vars.FALCON_REGION }}" || export FCS_EXIT_CODE=$?
          echo "exit-code=$FCS_EXIT_CODE" >> $GITHUB_OUTPUT

      - name: Upload image scan results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: image-scan-results
          path: ./image-scan-results.sarif
          if-no-files-found: warn
          retention-days: 3

      - name: Upload SARIF report to GitHub Code scanning
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 #v4.38.0
        if: always()
        with:
          sarif_file: ./image-scan-results.sarif
          category: "fcs_image_scanning"

      - name: Verify image was built
        run: |
          docker images | grep crwd/ubuntuweb